### ISSUE TITLE
Not active on first display

### ISSUE THREAD

**Issue by cdefy** [supraniti/vue-dnd-zone#4]
Hi,

After my first message about the use with Nuxt, I would like to thank you again for your work. I've been playing with it a bit and it's pretty smooth.

But I'm facing an issue that I don't see on your [demo project](https://supraniti.github.io/vue-dnd-zone/). When I'm loading the app for the first time, the DND on the index doesn't work. I need to visit another page then come back to be able to drag n' drop.
If I have the dnd-zone on another page, then when I go to it, it works just fine. But (as for the index), if I reload the page, I've got the same bug.

Any idea, advice or help will be appreciated :)
BR

**Comment by supraniti** [comment]
Would love to help, can you post a link to codesandbox with a similar code so i can check the bug?

**Comment by cdefy** [comment]
Thank you @supraniti for your quick answer. I'll try to find the time asap to build a codesandbox project.

**Comment by cdefy** [comment]
Hi @supraniti ,

Sorry I never took the time to do a codesandbox (anyway I tried to build one for another person and never managed to make it work, was stuck on the homepage of the test project).

Aaanyway, the bug seems to be fixed so I'll closed the issue.
